[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1python go.py
framework = arduino

monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = direct

build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    adafruit/Adafruit LSM6DS@^4.7.0
    adafruit/Adafruit Unified Sensor@^1.1.15