; =============================================================
;  PlatformIO Project Configuration
;  Board : Unexpected Maker ProS3 (ESP32-S3)
;  App   : IMU logger + WiFi TCP server
; =============================================================

[env:pros3]
platform  = espressif32
board     = um_pros3
framework = arduino

; Serial monitor
monitor_speed   = 115200
monitor_port    = COM6
upload_port     = COM6
monitor_dtr     = 0
monitor_rts     = 0
monitor_filters = direct

; Build flags
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1    ; Required for native USB serial on ESP32-S3

; Libraries
lib_deps =
    adafruit/Adafruit LSM6DS @ ^4.7.0
    adafruit/Adafruit Unified Sensor @ ^1.1.15