; =============================================================
;  PlatformIO Project Configuration
;  Board : Unexpected Maker ProS3 (ESP32-S3)
;  App   : IMU logger + WiFi TCP server
; =============================================================

[env:um_pros3]
platform = espressif32
board = um_pros3
framework = arduino

monitor_speed = 115200
upload_speed = 921600

build_flags =
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1

lib_deps =
    adafruit/Adafruit LSM6DS
    adafruit/Adafruit Unified Sensor